### ISSUE TITLE
Functionality restricted | Update needed | updating of swversion not working / resetting to default value

### ISSUE THREAD

**Issue by ma-mod** [diyhue/diyHue#551] opened 2020-12-25 14:03 UTC
**Describe the issue**

Hello at first, thank you for the answer in the first issue, which was unfortunately automatically closed due to the wrong template.
I've tried both options you mentioned:
1) use Hue Essentials App to update: It is not working, its hanging on the "searching for updates" page for ininite time.
2) change swversion parameter in config.json: I've changed it from: "swversion": "1939070020" to "swversion": "1941132070" which is the newest accordingly to the [change notes from philips](https://www.philips-hue.com/en-us/support/release-notes/bridge). Unfortunately after a restart of the hue-emulator, its changed back to the old version. I've also tried to stop the service before changing. Any clue why or what I am doing wrong?

**Steps you tried**

**How we can help**

Is there any trick to get this new swversion line applied to the hue-emulator?

**Logs**

unfortunately im not using the docker version yet, still the native one. running on a x64 ubuntu 18.04 CT under Proxmox/QEMU/KVM Virtualization

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): x64/x86
 - Docker image version (Ex: latest, arm-05f043b, 128): ---
 - OS (Ex: Windows 10, Ubuntu Buster): Ubuntu 18.0.4 LTS
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): PC/Server

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

(PS: This has nothing to do with my issue: but just for your information - when opening an issue on phone (android smartphone via chrome) I'm not getting any templates.)

**Comment by hdhdu** [comment] 2020-12-25 15:16
Hello,
I can confirm this problem. 
Additionally I have cleared all data of the app, uninstalled and reinstalled it. 
I also tried the config.json from the "dev"-Branch. But as mentioned above, every time I start the update in the App, it changes back to the old Version 19399070020.

**Comment by ma-mod** [comment] 2020-12-25 15:44
I've now trashed everything and completely sat it new up with docker. I am not able to connect the official Hue App with it, but Hue Essentials, Homeassistant and everything else is working now together again. Thanks anyway. 
But would be interesting why it wasnt working before

**Comment by alexyao2015** [comment] 2020-12-25 16:43
Templates are automatically populated when you select an issue type. The text prefilled in the text box is the template and it's expected that the user read all the text in the template.

You can either choose to manually adjust the swversion or try out the experimental branch to fix your issue.

**Comment by Mevel** [comment] 2020-12-26 10:07
In order to Update your swversion follow these steps:

    - Stop Emulator or Docker Container

    - edit config.json

    - change "swversion":"XXXXXXX" to “swversion”:“1941132080”

    - save

    - restart Service or Docker Container

Update Message should be gone.

[Discourse Instruction](https://diyhue.discourse.group/t/app-requires-update-of-hue-bridge-update-fails/233/2)

**Comment by hdhdu** [comment] 2020-12-27 06:43
@Mevel : Thanks a lot, your version number was the right one!  (but I had to delete data and cache in the hue app, before it worked finally.)
Whats your source to get the right version number?
Mine is this one: https://www.philips-hue.com/de-de/support/veroffentlichungshinweis/bridge
But the latest version number is missing, so it did not work. 
The version number in dev-branch of this project wasn't working aswell.
Thanks for your support!

**Comment by Lysdex** [comment] 2021-01-22 02:57
swversion change to “swversion”:“1941132080” did not fix genuine hue app issue for me

My hue app still refuses to find the diyhue bridge

**Comment by mariusmotea** [comment] 2021-01-22 18:50
@Lysdex you have an invalid certificate, you use docker and provided wrong mac address, or use a device with multiple interfaces and the installation script pick wrong interface for certificate generation.

**Comment by Lysdex** [comment] 2021-01-22 23:05
@mariusmotea 

pi@raspberrypi:~ $ curl https://127.0.0.1/api/nouser/config -v -k
* Expire in 0 ms for 6 (transfer 0x5728a0)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x5728a0)
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=NL; O=Philips Hue; CN=b827ebfffe90ee95
*  start date: Jan 22 22:50:41 2021 GMT
*  expire date: Jan 20 22:50:41 2031 GMT
*  issuer: C=NL; O=Philips Hue; CN=b827ebfffe90ee95
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /api/nouser/config HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.64.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 200 OK
< Server: nginx
< Date: Fri, 22 Jan 2021 23:05:15 GMT
< Content-type: application/json
< Content-Length: 227
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, OPTIONS, POST, PUT, DELETE
< Access-Control-Allow-Headers: X-Requested-With
< Access-Control-Allow-Headers: Content-Type
<
* Connection #0 to host 127.0.0.1 left intact
{"name":"Philips hue","datastoreversion":70,"swversion":"1941132080","apiversion":"1.35.0","mac":"b8:27:eb:90:ee:95","bridgeid":"B827EBFFFE90EE95","factorynew":false,"replacesbridgeid":null,"modelid":"BSB002","starterkitid":""}

Looks fine to me

**Comment by sascha777** [comment] 2021-01-24 18:50
> swversion change to “swversion”:“1941132080” did not fix genuine hue app issue for me
> 
> 
> 
> My hue app still refuses to find the diyhue bridge

I had the same problem with the swversion. I just queried my original bridge for the current version and used this in my config. Running smooth again. 
Wouldn't it be possible to do that automatically to apply hub update version number to the config?

**Comment by Lysdex** [comment] 2021-01-24 20:12
> > swversion change to “swversion”:“1941132080” did not fix genuine hue app issue for me
> > My hue app still refuses to find the diyhue bridge
> 
> I had the same problem with the swversion. I just queried my original bridge for the current version and used this in my config. Running smooth again.
> Wouldn't it be possible to do that automatically to apply hub update version number to the config?

What is the version number yours is? I dont have a hub to query

**Comment by sascha777** [comment] 2021-01-25 06:36
My Hue hub runs
`"swversion": "1942135050"`

**Comment by Rapti** [comment] 2021-01-25 14:35
I'm having this problem too. I installed diyHue using the official docker container. Changes to `swversion` and `apiversion` keep getting overwritten which prevents me from using the official Hue App or Razer Synapse. 
My actual Hue Bridge reports:

    "swversion":"1942135050",
    "apiversion":"1.42.0"
    
It doesn't matter whether I stop the container before making the changes.

**Comment by Lysdex** [comment] 2021-01-26 19:21
> I'm having this problem too. I installed diyHue using the official docker container. Changes to `swversion` and `apiversion` keep getting overwritten to older values which prevents me from using the official Hue App or Razer Synapse.
> My actual Hue Bridge reports:
> 
> ```
> "swversion":"1942135050",
> "apiversion":"1.42.0"
> ```
> 
> It doesn't matter whether I stop the container before making the changes.
> 
> EDIT: After a bunch of retries it suddenly worked. No idea why though.

Using your settings when i search for hue hub, it finds it for a milisecond then says no new hue bridge found.
Ive tried running it as a host install and on docker both with similar results.
Very annoying since it was working fine for so long!

**Comment by Lysdex** [comment] 2021-01-26 21:27
`2021-01-26 21:24:35,865 - root - DEBUG - Sending M-Search response to 192.168.1.162
2021-01-26 21:24:37,069 - root - DEBUG - Sending M-Search response to 192.168.1.162
2021-01-26 21:24:38,072 - root - DEBUG - Sending M-Search response to 192.168.1.162
192.168.1.162 - - [26/Jan/2021 21:24:40] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:24:40] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:24:45] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:24:45] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
2021-01-26 21:24:48,845 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2021-01-26 21:24:49,123 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
192.168.1.162 - - [26/Jan/2021 21:24:50] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:24:50] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:24:55] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:24:55] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:00] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:00] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:05] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:05] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:10] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:10] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:15] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:15] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
2021-01-26 21:25:18,914 - root - DEBUG - Sending M-Search response to 192.168.1.250
2021-01-26 21:25:19,178 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2021-01-26 21:25:19,465 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
192.168.1.162 - - [26/Jan/2021 21:25:20] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:20] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:25] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:25] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:30] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:30] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
2021-01-26 21:25:32,449 - root - DEBUG - Sending M-Search response to 192.168.1.162
2021-01-26 21:25:33,352 - root - DEBUG - Sending M-Search response to 192.168.1.162
2021-01-26 21:25:34,156 - root - DEBUG - Sending M-Search response to 192.168.1.162
2021-01-26 21:25:34,959 - root - DEBUG - Sending M-Search response to 192.168.1.162
192.168.1.162 - - [26/Jan/2021 21:25:35] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:35] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
2021-01-26 21:25:36,553 - root - DEBUG - Sending M-Search response to 192.168.1.162
2021-01-26 21:25:37,756 - root - DEBUG - Sending M-Search response to 192.168.1.162
192.168.1.162 - - [26/Jan/2021 21:25:40] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:40] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.209 - - [26/Jan/2021 21:25:42] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:45] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:45] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
2021-01-26 21:25:49,416 - root - DEBUG - Sending M-Search response to 192.168.1.250
2021-01-26 21:25:49,519 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2021-01-26 21:25:49,808 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
192.168.1.162 - - [26/Jan/2021 21:25:50] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:50] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
2021-01-26 21:25:50,419 - root - DEBUG - Sending M-Search response to 192.168.1.250
2021-01-26 21:25:51,423 - root - DEBUG - Sending M-Search response to 192.168.1.250
2021-01-26 21:25:52,226 - root - DEBUG - Sending M-Search response to 192.168.1.250
192.168.1.162 - - [26/Jan/2021 21:25:55] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:25:55] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:26:00] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:26:00] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:26:05] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:26:05] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:26:10] "GET /api/9c01f1b699f211eabacbb827eb90ee95/lights HTTP/1.1" 200 -
192.168.1.162 - - [26/Jan/2021 21:26:10] "GET /api/9c01f1b699f211eabacbb827eb90ee95/sensors HTTP/1.1" 200 -
`
My debug output. I dont see the hub getting hit when hue app is scanning for hub

**Comment by juanesf** [comment] 2021-01-27 20:39
Can taste with diyhue/core:dev or diyhue/core:amd64-dev

**Comment by g-philipp** [comment] 2021-03-23 21:38
> In order to Update your swversion follow these steps:
> 
> ```
> - Stop Emulator or Docker Container
> 
> - edit config.json
> 
> - in key "config" --> change "swversion":"XXXXXXX" to “swversion”:“1941132080”
> - Note: not for every Light!
> - save
> 
> - restart Service or Docker Container
> ```
> 
> Update Message should be gone.
> 
> [Discourse Instruction](https://diyhue.discourse.group/t/app-requires-update-of-hue-bridge-update-fails/233/2)


For now you have to use swversion:1943185030

**Comment by Jimbo145** [comment] 2021-05-04 22:20
I think this can be closed, as the fix was merged with #598

**Comment by mariusmotea** [comment] 2021-05-06 08:42
Yes, i also update the swversion in master with the one from 28Apr release.

**Closed by mariusmotea** 2021-05-06 08:42 UTC
Labels: Help Request
