### ISSUE TITLE
Tasmota light status switches to OFF or unreachable and no WW available

### ISSUE THREAD

**Issue by tomvanderputte** [diyhue/diyHue#402] opened 2020-05-19 19:39 UTC
There are two issues, that might be related, so I'll post them in one ticket. If I need to split them, let me know.

Here's my setup:

regular Hue: 
V1 bridge + several Philips + Ikea lights, all white or "ambiance"
Raspberry Pi 3b+ with diyHue running in Docker.

1 LSC Smart connect GU10 RGBWW spot flashed with Tasmota

After downloading the new Hue app, I can actually add the diyHue bridge to the new app, not the old (took me a while, but sounds logical). It sees the tasmota lamp, and I can use the color wheel and the brightness to control it. It works!

However, even when I'm watching the lamp status in the app, it switches to off after 5 seconds or so. I can set the status back on, and continue working with it, but still it's odd. The same goes for the Hue essentials app, but there the status changes to 'Unreachable'. But I can still turn it on. 

Then in the official hue app, it shows no white color temp selector (cold or warm white).
The hue essentials app has the problem that I see the white color temp slider, but it doesn't work. Further more, I cannot set the color using the color spiral. I can only control brightness. 

Is it perhaps because the tasmota device and FW supports additional WW LEDS, but this is not yet implemented in the tasmota protocol? Does this also trigger the problem with the lamp status going out/offline?

If it helps I could add the parameters that the internal web-app uses when changing the light colors?

**Comment by alexyao2015** [comment] 2020-05-21 01:11
Dupe of #370

**Closed by alexyao2015** 2020-05-21 01:11 UTC
