### ISSUE TITLE
Cannot detect bridge in the network (neither with manual IP config)

### ISSUE THREAD

**Issue by noisemaker00** [diyhue/diyHue#314] opened 2019-12-24 15:09 UTC
**Describe the bug**
When I open the Philips Hue app automatic scanning start. The message "Bridge found" appears for less than a seconds, then error message "No bridge found".
The same if I manually set the IP using the button below "Search" on app first screen.

The bridge scan works with Hue Essentials app

**Comment by alexyao2015** [comment] 2019-12-25 04:05
Try the beta branch, use the manual install method or find the beta docker image

**Comment by mariusmotea** [comment] 2019-12-25 13:57
Probably duplicate of https://diyhue.discourse.group/t/unable-to-find-bridge-or-add-new-deconz-lights-from-hue-app/45/9

Or at last the behavior is the same. Check the certificate CN like it did there. Probably you play with more than one interface.

**Comment by ryancasler** [comment] 2019-12-26 16:32
That's exactly what fixed it for me.

**Comment by noisemaker00** [comment] 2019-12-26 23:12
So I need to reinstall due to certificate error?
And I need to reinstall from master or beta branch?

**Comment by alexyao2015** [comment] 2019-12-26 23:46
Just delete the certificate and restart diyhue

**Comment by noisemaker00** [comment] 2019-12-27 22:21
I tried both with 'delete and restart' and 'full re-installation', but nothing changed.

**Comment by ryancasler** [comment] 2019-12-28 20:56
When you did a full re-installation, what did you bring over?  Your config.json file or nothing at all?  When you did the full install, did you delete the /opt/hue-emulator folder before re-installing?  You're trying to get rid of the certificate the bridge is using as that is most likely corrupted in some way.

Your symptoms is EXACTLY the same as I was experiencing.  You could also try the Hue Essentials app instead.  For some reason, I was always able to add the bridge into that app.  I guess it's less "picky" than the Hue app.

**Comment by alexyao2015** [comment] 2020-01-15 02:03
Since there has been no reply, I will be closing this issue.

**Closed by alexyao2015** 2020-01-15 02:03 UTC
