### ISSUE TITLE
Deconz + diyHue: Wrong swversion

### ISSUE THREAD

**Issue by oskar1999** [diyhue/diyHue#493] opened 2020-11-09 16:27 UTC
**Describe the bug**
So I've got a Deconz instance running which is connected to diyHue.
I'm trying to setup an entertainment area in the official Hue app but it always says that I need to update my bulbs firmware.
My environment consist of different bulbs (Hue, Tradfri) but I only want to use supported Hue bulbs for the entertainment area.
The hue app reports swversion 1.46.13_r26312 (for all other bulbs too) but I updated the bulb to 1.6.xxxxxxx.
I also tried to stop the container, edit the config.json and change the software version but it keeps getting overwritten once I start the container again. That happens for all the other bulbs too.

**To Reproduce**
Connect bulbs via Deconz to diyHue and add the emulated bridge to the Hue app.

**Expected behavior**
I expect diyHue to report the real swversion of the bulb or at least the version I configured in the config.json. Sadly the swversion always gets overwritten once the container starts.

**Logs**
The logs don't show anything interesting.

**Docker Info (please complete the following information):**
 - Architecture: ARM
 - Docker image version: latest
 - Hardware: Raspberry Pi 3B+

**Comment by mariusmotea** [comment] 2020-11-09 17:09
First bad news that i will give you is that entertainment protocol stops in the hue emulator, from there Deconz calls are made using hue api protocol over http, so it is not that fast. Loking in the code i don't see from where the swversion is updated:
https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py#L989
At this line i see only light state is updated, maybe you edit the config.json file while the hue emulator service was still running?

**Comment by alexyao2015** [comment] 2020-11-09 17:17
Well yes, the firmware of bulbs are currently hardcoded [see here](https://github.com/diyhue/diyHue/blob/af279173c2eacca072895f8ec394e50721480138/src/core/functions/__init__.py#L15). I don't believe its the firmware number of the bulb itself that is causing the issue, however as I am able to use entertainment mode just fine with the version reported. Its more likely an issue with the deconz protocol using a nonstandard bulb type.

**Comment by alexyao2015** [comment] 2020-11-09 17:17
#463

**Comment by Sapd** [comment] 2020-11-11 15:02
I have exactly the same Problem.

**Comment by oskar1999** [comment] 2020-11-11 17:31
That did the trick! Changing it to LCT015 lets me create the entertainment area.
But now once I start syncing via the Hue Sync Mac App, the app looses connection to the bridge.
Is that related to deconz? If it's only a small delay, I could deal with that for now.

**Comment by Sapd** [comment] 2020-11-11 18:27
> That did the trick! Changing it to LCT015 lets me create the entertainment area.
> But now once I start syncing via the Hue Sync Mac App, the app looses connection to the bridge.
> Is that related to deconz? If it's only a small delay, I could deal with that for now.

I also tried the Mac App, and it worked for me. Maybe close it again, and delete the cache of the App:
$HOME/Library/Application Support/com.lighting.huesync
$HOME/Library/Caches/Signify/huesync

However, I experimented a bit, and the delay is really humongous. It's like multiple seconds. So no real option of using hue entertainment this way :(

**Comment by alexyao2015** [comment] 2020-11-11 18:56
This goes back to the fact that unless there is an api that isn't rate limited, there is nothing we can do.

**Closed by alexyao2015** 2020-11-11 18:56 UTC

**Comment by Sapd** [comment] 2020-11-11 19:01
> This goes back to the fact that unless there is an api that isn't rate limited, there is nothing we can do.

However, this is not what this issue is about. So not sure why you closed it. The slow responsiveness, is just a side-issue.

The issue is, that using the white & ambience color lamps, the entertainment function does **entirely** not work out-of-the-box.
I made it working, by setting the model name explicitly from LCA001 to LCT015 here https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py#L330

**Comment by alexyao2015** [comment] 2020-11-11 19:04
This is in fact the same issue as #463 as mentioned in earlier comments
