### ISSUE TITLE
diyhue not starting after update

### ISSUE THREAD

**Issue by AlexKusnezov** [diyhue/diyHue#296] opened 2019-11-20 20:53 UTC
**Describe the bug**
After performing an update diyhue isn't starting anymore :(

**Logs**
I tried to run the emulator manually and this is what i got
```Traceback (most recent call last):
  File "./HueEmulator3.py", line 1904, in <module>
    initialize()
  File "./HueEmulator3.py", line 189, in initialize
    sanitizeBridgeScenes()
  File "./HueEmulator3.py", line 208, in sanitizeBridgeScenes
    if "lightstates" in bridge_config["scenes"][scene] and len(bridge_config["scenes"][scene]["lightstates"]) == 0: # empty scenes are useless
KeyError: '100'
```

Any idea what to do or how to fix?

**Comment by mariusmotea** [comment] 2019-11-21 07:56
Even after another restart you have this error? I think you had one invalid group scene caused by one group beying deleted and also the scene (nr 100 in your case) was deleted [here](https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py#L198). If you restart the service the scene will not be anymore in iteration.

**Comment by mariusmotea** [comment] 2019-11-21 07:59
closed by mistake.

**Comment by AlexKusnezov** [comment] 2019-11-21 08:09
> Even after another restart you have this error? I think you had one invalid group scene caused by one group beying deleted and also the scene (nr 100 in your case) was deleted [here](https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py#L198). If you restart the service the scene will not be anymore in iteration.

thanks for the hint, yes I tried to restart it = not working. I'll try to edit my config manually.

**Comment by mariusmotea** [comment] 2019-11-21 08:32
The error is the same?

**Comment by AlexKusnezov** [comment] 2019-11-21 08:35
@mariusmotea awesome, I'll try it out when I'm back home.

**Comment by alexyao2015** [comment] 2019-11-21 13:58
I'm going to close this. I fixed the same bug earlier using a different method so try that if the latest doesn't work.

**Closed by alexyao2015** 2019-11-21 13:58 UTC

**Comment by AlexKusnezov** [comment] 2019-11-21 18:34
@mariusmotea @alexyao2015 thanks guys, you saved me, it worked right away!
