### ISSUE TITLE
Cannot connect to hub with Sleep as Android

### ISSUE THREAD

**Issue by MaxiBerdy** [diyhue/diyHue#276] opened 2019-11-11 11:45 UTC
Hello again,
This is a followup on #275, thank you for the quick answer.
(Now I can setup a room without a problem on the official Hue app !)

**Describe the bug**
Now that the docker works out of the box, I still have a problem to connect Sleep as Android to the diyHue hub. It looks like the app cannot pair with the hub. It usually can find the hub when searching for it, but it either cannot connect to the hub (displaying "Connecting..."), or does connect and asks to push the hub confirm button, but as soon as I activate it through the web interface, the progress bar on the app gets stuck and nothing happens.

**To Reproduce**
1. Set up a diyHue and a light (adding the light to the network etc)
2. Set up the room with the Philips Hue app
3. Open Sleep as Android, press the three striped icon, and go to Settings
4. Press the Advanced button in the "Sleep as Android integration" tab then press "Smart light"
5. Scroll down to the "Philips Hue" section, press "Advanced" and then "Philips Hue is disconnected"
6. Wait for the search to complete, and then press the Philips Hue Bridge
7. Either:
7a. You get stuck in the "Connecting..." pop-up
8. Or:
8a. It displays the button and asks you to press it to pair
8b. Activate the button on the web interface of the Hub
8c. The progress bar on the Sleep as Android app gets stuck.

**Expected behavior**
It should always show up the pairing dialog in the first place, and then it should pair without any problem.

**Logs**
I ran the Python script in debug mode, here is the log :
https://pastebin.com/GLUUcmPn

**Additional context**
- Running latest diyHue Python script to this date on Kubuntu 19.04, installed through the automated install script available on the ReadTheDocs webpage
- Using Sleep as Android latest version (20190925)

**Comment by mariusmotea** [comment] 2019-11-11 15:24
Today i made a new commit, can you ensure you are using the last version? What is the output if you perform same request (from debug log: `curl 192.168.1.25/api/null`) ?

**Comment by lacaulac** [comment] 2019-11-11 15:35
We were running on the latest version when trying to use Sleep as Android. Unfortunately MaxiBerdy's not at my place anymore and therefore we can't test anything right now. The same bug occurred yesterday before today's patches (so at the same time we submitted the Docker version issue).

**Comment by mariusmotea** [comment] 2019-11-11 15:47
Based on the output it fail at the simple config query where the output must look like this:

```{"name":"Philips hue","datastoreversion":70,"swversion":"1935074050","apiversion":"1.35.0","mac":"1a:4e:92:35:ba:24","bridgeid":"1A4E92FFFE35BA24","factorynew":false,"replacesbridgeid":null,"modelid":"BSB002","starterkitid":""}```

**Comment by alexyao2015** [comment] 2019-11-11 16:18
@mariusmotea The fix is #257

**Comment by alexyao2015** [comment] 2019-11-11 16:19
Haven't wanted to merge it until we knew everything worked properly

**Comment by alexyao2015** [comment] 2019-11-11 16:20
Dupe of #19

**Closed by alexyao2015** 2019-11-11 16:20 UTC

**Comment by mariusmotea** [comment] 2019-11-11 16:21
From attached log the pair process is not completed. No username is created on bridge to get the entire configuration.

**Comment by alexyao2015** [comment] 2019-11-11 16:25
I'm pretty sure the username exists. It's just that those apps by that dev don't like lightstates showing up. If he posts the config we'll know for sure

**Comment by lacaulac** [comment] 2019-11-11 16:34
Do you need the config.json file or the response from /api/null?

**Comment by alexyao2015** [comment] 2019-11-11 16:44
No, just update and see if its working now. Just merged the pull.

**Comment by mariusmotea** [comment] 2019-11-11 16:48
Also wipe the application data from Android settings.

**Comment by MaxiBerdy** [comment] 2019-11-11 17:18
Thank you for the answers, gonna try tonight and I'll let you know.
BTW @mariusmotea, do you mean wiping my Sleep as Android data ? I will try without first because all my settings are saved on the app and I don't really want to make it all again..
If you meant the Philips Hue app, I got the hang of it and always wiped the data to be sure it was starting from 0 !

**Comment by alexyao2015** [comment] 2019-11-11 17:20
You likely don't have to wipe sleep

**Comment by mariusmotea** [comment] 2019-11-11 17:26
I made a test now with my phone and my lights appear in the application. In debug i have a successful pair. I think i update my raspberry pi 2 days ago, so it not very last version.
```
192.168.10.20 - - [11/Nov/2019 19:23:34] "GET /api/null HTTP/1.1" 200 -
192.168.10.20 - - [11/Nov/2019 19:23:34] "POST /api/ HTTP/1.1" 200 -
2019-11-11 19:23:34,357 - root - INFO - in post method
2019-11-11 19:23:34,357 - root - INFO - /api/
2019-11-11 19:23:34,358 - root - INFO - b'{"devicetype":"SleepAsAndroid#HTC U11"}'
2019-11-11 19:23:34,360 - root - INFO - [
    {
        "success": {
            "username": "fd4777e204a711eab463dca6320059d6"
        }
    }
]
192.168.10.20 - - [11/Nov/2019 19:23:34] "GET /api/fd4777e204a711eab463dca6320059d6 HTTP/1.1" 200 -
192.168.10.20 - - [11/Nov/2019 19:23:34] "GET /api/fd4777e204a711eab463dca6320059d6 HTTP/1.1" 200 -
2019-11-11 19:23:35,473 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2019-11-11 19:23:35,817 - root - INFO - sync with lights
```

**Comment by alexyao2015** [comment] 2019-11-11 17:29
Do you have any scenes? The bug only happens if there were scenes. The pull fixed that issue.

**Comment by mariusmotea** [comment] 2019-11-11 17:32
I did not go forward. I saw the groups, the successful pair and i stop there. From the logs posted today there was an incomplete pair process.

**Comment by MaxiBerdy** [comment] 2019-11-11 21:02
Okay set up everything on my own computer, and there goes an other error !
I cannot get past the Philips Hue app setup. I guess it's because I'm running a linux docker container on Windows or something like that ?

**Describe the bug**
When trying to find the diyHue hub with the Philips Hue application, it searches for the hub, shows that it found it for an instant (like 0.1 sec) and then shows it cannot find any hub.

**To Reproduce**
Steps to reproduce the behavior:
1. Set up a diyHue linux docker on windows using this command :
`run -d --name "diyHue" --restart="always" --network="bridge" -v d:/location/to/export/:/opt/hue-emulator/export/ -e MAC='XX:XX:XX:XX:XX' -e IP='XXX.XXX.XXX.XXX' -e 'DEBUG=true' -p 80:80/tcp -p 443:443/tcp -p 1900:1900/udp -p 2100:2100/udp -p 1982:1982/udp diyhue/core:latest`
2. Check that localhost does connect to the web interface, and that PC's IP does connect to web interface using an other device (eg. an Android phone)
3. Use the Philips Hue app and hit search for hub
4. Wait a bit and see that the dialog quickly turns green then red, saying in the end, that it can't find the hub

**Expected behavior**
I know the wiki says I shouldn't run a docker container on Windows but I hoped it could work..

**Logs**
I ran the docker container in debug mode, here is the log :
https://pastebin.com/5Gy69D4V

**Additional context**
- Running latest diyHue docker with the command shown above, on Windows 10

**Comment by alexyao2015** [comment] 2019-11-11 21:08
That's an issue with your config. Clear it and try again. If you're still having issues, try slack

**Comment by MaxiBerdy** [comment] 2019-11-11 21:15
Clearing the config doesn't fix the issue...
I will come later that night, doing something in the moment !

**Comment by MaxiBerdy** [comment] 2019-11-11 22:36
Okay I fixed my issue, for some reason, I was typing my mac address with `-e MAC='XX-XX-XX-XX-XX-XX'` instead of `-e MAX='XX:XX:XX:XX:XX:XX'`...

Now back to the starting point, I can't get past the Sleep as Android smart light setup..
I can give you some more logs now, it can't go past :

`172.17.0.1 - - [11/Nov/2019 22:35:33] "GET /api/config HTTP/1.1" 200 -
172.17.0.1 - - [11/Nov/2019 22:35:42] "GET /api/null HTTP/1.1" 200 -`
