### ISSUE TITLE
Philips "Wakeup" /  "go to sleep" routines not working

### ISSUE THREAD

**Issue by Zappelphilipp** [diyhue/diyHue#278] opened 2019-11-12 17:42 UTC
**Describe the bug**
setting a routine in the philips hue app for a specific time throws exceptions in diyHue when time trigger fires.

**To Reproduce**
1. open tab "routines" in philips hue app. 
2. choose ether "good night" or " wake up" routine (not sure how its called exactly in the english version)
3. set time and room as well as fading time
4. save
5. wait for trigger reaching set time
6. nothing happens except exceptions thrown in log

**Expected behavior**
should fade out (or in) all lights set in routine

**Logs**
```

  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
,  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/sessions.py", line 512, in request
,    return request('put', url, data=data, **kwargs)
,    sendRequest("/api/" +    list(bridge_config["config"]["whitelist"])[0] + action["address"], action["method"], json.dumps(action["body"]))
,Traceback (most recent call last):
,    self.handle()
,127.0.0.1 - - [12/Nov/2019 18:06:00] "PUT /api/841302e0056c11ea8c1a0242ac110003/sensors/7/state HTTP/1.1" 200 -
,127.0.0.1 - - [12/Nov/2019 18:06:00] "PUT /api/web-ui-26382/groups/0/action HTTP/1.1" 200 -
,----------------------------------------
,Exception happened during processing of request from ('127.0.0.1', 59232)
,  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
,    self.finish_request(request, client_address)
,  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
,    self.RequestHandlerClass(request, client_address, self)
,  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
,  File "/usr/lib/python3.7/http/server.py", line 426, in handle
,    self.handle_one_request()
,  File "/opt/hue-emulator/HueEmulator3.py", line 1775, in do_PUT
,    method()
,    splitLightsToDevices(url_pices[4], {}, bridge_config["scenes"][put_dictionary["scene"]]["lightstates"])
,KeyError: 'lightstates'
,Exception happened during processing of request from ('127.0.0.1', 59230)
,  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 600, in urlopen
,    chunked=chunked)
,  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 384, in _make_request
,    six.raise_from(e, None)
,  File "<string>", line 2, in raise_from
,  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 380, in _make_request
,    httplib_response = conn.getresponse()
,    response.begin()
,  File "/usr/lib/python3.7/http/client.py", line 296, in begin
,  File "/usr/lib/python3.7/http/client.py", line 265, in _read_status
,    raise RemoteDisconnected("Remote end closed connection without"
,    version, status, reason = self._read_status()
,  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
,  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/adapters.py", line 445, in send
,  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/connectionpool.py", line 638, in urlopen
,    _stacktrace=sys.exc_info()[2])
,  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/util/retry.py", line 367, in increment
,    timeout=timeout
,
,http.client.RemoteDisconnected: Remote end closed connection without response
,During handling of the above exception, another exception occurred:
,    raise six.reraise(type(error), error, _stacktrace)
,  File "/usr/local/lib/python3.7/dist-packages/urllib3-1.23-py3.7.egg/urllib3/packages/six.py", line 685, in reraise
,    raise value.with_traceback(tb)
,urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
,  File "/opt/hue-emulator/HueEmulator3.py", line 1809, in do_PUT
,    rulesProcessor(url_pices[4], current_time)
,  File "/opt/hue-emulator/HueEmulator3.py", line 661, in rulesProcessor
,  File "/opt/hue-emulator/functions/request.py", line 16, in sendRequest
,  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/api.py", line 126, in put
,    response = requests.put(url, data=bytes(data, "utf8"), timeout=timeout, headers=head)
,  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/api.py", line 58, in request
,    return session.request(method=method, url=url, **kwargs)
,    resp = self.send(prep, **send_kwargs)
,  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/sessions.py", line 622, in send
,  File "/usr/local/lib/python3.7/dist-packages/requests-2.19.1-py3.7.egg/requests/adapters.py", line 495, in send
,    r = adapter.send(request, **kwargs)
,    raise ConnectionError(err, request=request)
,requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
,{"ok"}
```

**Comment by alexyao2015** [comment] 2019-11-12 23:39
Dupe of #233

**Closed by alexyao2015** 2019-11-12 23:39 UTC
