### ISSUE TITLE
Current Light state is not saved when saving scene in Hue Essentials App

### ISSUE THREAD

**Issue by RudolfAchter** [diyhue/diyHue#210] opened 2019-10-03 08:41 UTC
**Describe the bug**
I do some Setting in a room in hue essentials app. I try to save this as a "scene". I say "save current light state" i name it "KitchenColors". Scene is saved in hue emulator. I see a new section in "config.json" but lightstates is empty.

        "31": {
            "appdata": {
                "data": "DYfPa_r03",
                "version": 1
            },
            "lastupdated": "2019-10-03T08:17:24",
            "lights": [
                "6",
                "7"
            ],
            "lightstates": {},
            "locked": false,
            "name": "KitchenColors",
            "owner": "hueessdce54511e9b51a00163e2ce65c",
            "picture": "",
            "recycle": false,
            "version": 2
        },

I tried to **manually** write lightstates in another Scene (Scene ID 22) Name "Salzlampe". This works as expected but is not comfortable to write config manually:

        "22": {
            "appdata": {
                "data": "OiGoI_r01",
                "version": 1
            },
            "lastupdated": "2019-10-01T20:53:10",
            "lights": [
                "1",
                "2",
                "3",
                "4"
            ],
            "lightstates": {
                "1": {
                    "bri": 50,
                    "colormode": "ct",
                    "effect": "none",
                    "hue": 5482,
                    "on": true,
                    "reachable": true,
                    "sat": 254
                },
                "2": {
                    "bri": 50,
                    "colormode": "ct",
                    "effect": "none",
                    "hue": 5482,
                    "on": true,
                    "reachable": true,
                    "sat": 254
                },
                "3": {
                    "bri": 254,
                    "colormode": "ct",
                    "effect": "none",
                    "hue": 5482,
                    "on": true,
                    "reachable": true,
                    "sat": 254
                },
                "4": {
                    "bri": 95,
                    "colormode": "ct",
                    "effect": "none",
                    "hue": 21845,
                    "on": true,
                    "reachable": true,
                    "sat": 254
                }
            },
            "locked": false,
            "name": "Salzlampe",
            "owner": "hueess22e48c11e9b63000163e2ce65c",
            "picture": "",
            "recycle": false,
            "version": 2
        },

**To Reproduce**

My setup is diyhue hue-emulator -> esp8266 -> milight lights

1. Open Hue Essentials on Smart Phone
2. Configure some Light Settings
3. Save Current Light Settings as new scene
4. Look in config.json in hue-emulator
5. find new scene section -> "lightstates" is empty

**Expected behavior**
I expect current lightstates to be saved in the scene. Using these lightstates afterwards works already. I tested it by writing my own lightstates config in config file

**Logs**
If applicable, provide output logs. These can be obtained via manually running HueEmulator3.py with `python3 HueEmulator3.py`.

See all the files in zip
[2019-10-03 hue-emulator debug.zip](https://github.com/diyhue/diyHue/files/3685138/2019-10-03.hue-emulator.debug.zip)

i also added a pcap Capture (tcpdump). when you look at the necessary HTTP requests you can see my smartphone sends this:

//Sent by my Smartphone

    POST /api/hueessdce54511e9b51a00163e2ce65c/scenes HTTP/1.1
    Accept-Charset: UTF-8
    Accept: */*
    User-Agent: Ktor client
    Content-Length: 102
    Host: 192.168.1.16
    Connection: Keep-Alive
    Accept-Encoding: gzip

    {"name":"KitchenColors","lights":["6","7"],"recycle":false,"appdata":{"version":1,"data":"DYfPa_r03"}}HTTP/1.1 200 OK

for me it looks like it only says **which** lights it wants to save, but not what state these lights are. Don't know if this behaviour is different with original Hue Bulbs. This is what i see with MiLight.

But you should be able to get Current State of these Lights yourselb by asking hue-emulator itself and then saving this state

**Additional context**

If there are further questions, you can contact me here on gitHub

**Comment by Thomas-Vos** [comment] 2019-10-04 22:15
This looks like a bug. When creating a scene the light states should be set to the current states. See official Hue documentation:
https://developers.meethue.com/develop/hue-api/4-scenes/#create-scene
> Creates the given scene with all lights in the provided lights resource. For a given scene the current light settings of the given lights resources are stored. If the scene id is recalled in the future, these light settings will be reproduced on these lamps.

**Comment by mariusmotea** [comment] 2019-10-05 15:22
I think i found the root cause. I when i store the lights states i loop with scene/{id}/lightstates and these must be created first. I will create a fix very soon.

**Comment by mariusmotea** [comment] 2019-10-05 15:51
@Thomas-Vos i saw on my firsts tries requests to store the lights states with a delay of 6-7 seconds after scene creation. Now i want to test my fix but the request to store the lights states is not coming anymore.

```
192.168.10.20 - - [05/Oct/2019 18:46:55] "POST /api/hueessd0d7b011e9b615dca6320059d6/scenes HTTP/1.1" 200 -
2019-10-05 18:46:55,804 - root - INFO - in post method
2019-10-05 18:46:55,804 - root - INFO - /api/hueessd0d7b011e9b615dca6320059d6/scenes
2019-10-05 18:46:55,805 - root - INFO - b'{"name":"Scena sss","lights":["4"],"recycle":false,"appdata":{"version":1,"data":"OWepE_r01"},"picture":"f-4653757398"}'
2019-10-05 18:46:55,806 - root - INFO - [
    {
        "success": {
            "id": "138"
        }
    }
]
192.168.10.20 - - [05/Oct/2019 18:46:57] "GET /api/hueessd0d7b011e9b615dca63200xxxx HTTP/1.1" 200 -
192.168.10.20 - - [05/Oct/2019 18:47:08] "GET /api/hueessd0d7b011e9b615dca63200xxxx HTTP/1.1" 200 -
2019-10-05 18:47:09,714 - root - INFO - sync with lights
2019-10-05 18:47:09,720 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.10.12:80
2019-10-05 18:47:12,872 - urllib3.connectionpool - DEBUG - http://192.168.10.30:80 "GET /state?light=2 HTTP/1.1" 200 90
2019-10-05 18:47:12,896 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.10.30:80
2019-10-05 18:47:12,922 - urllib3.connectionpool - DEBUG - http://192.168.10.30:80 "GET /state?light=3 HTTP/1.1" 200 90
```

**Comment by Thomas-Vos** [comment] 2019-10-05 17:42
Hi @mariusmotea,
Hue Essentials does not use a storelightstate command for this. What @RudolfAchter means is that the light states are not set to the current state. When a scene is created, like your example, it should store the current light state in the scene. So there is no need for an additional storelightstate command. If this is not clear feel free to message me on Slack.

**Comment by mariusmotea** [comment] 2019-10-05 17:44
Ahh, i go it now. So if no lightstates are declared during scene creation the current values will be stored.

**Comment by mariusmotea** [comment] 2019-10-05 18:04
I test now and it is fixed with last commit.

**Closed by mariusmotea** 2019-10-05 18:04 UTC

**Comment by RudolfAchter** [comment] 2019-10-06 12:10
I also testet it. "Save current LightState" works as expected now :-)
